# Nome da aplicacao
spring.application.name=pecaja-api

# Configuracoes do Banco de Dados H2 (Em Memoria)
spring.datasource.url=jdbc:h2:mem:pecajadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuracoes do Hibernate onde cria as tabelas (JPA)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilitar a interface web do banco de dados (H2 Console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console